### PR TITLE
New inheritance structure for `rsplit` objects and updated `complement()` methods

### PR DESCRIPTION
**Pull request by hfrick**
This is to address #213 as laid out in [this comment](https://github.com/tidymodels/rsample/issues/213#issuecomment-771637109).

### CODE REVIEW

**Comment by topepo** [comment]
```r
> revdep_check(num_workers = 20)
── INIT ────────────────────────────────────────────────────────────────── Computing revdeps ──
── INSTALL ────────────────────────────────────────────────────────────────────── 2 versions ──
Installing CRAN version of rsample
Installing DEV version of rsample
Installing 4 packages: parallelly, cpp11, dplyr, furrr
── CHECK ────────────────────────────────────────────────────────────────────── 23 packages ──
✓ ivdesc 1.0.0                           ── E: 0     | W: 0     | N: 0                        
✓ butcher 0.1.2                          ── E: 0     | W: 0     | N: 1                        
✓ gesttools 1.0.1                        ── E: 0     | W: 0     | N: 0                        
✓ probably 0.0.6                         ── E: 0     | W: 0     | N: 0                        
✓ embed 0.1.4                            ── E: 0     | W: 0     | N: 0                        
✓ baguette 0.1.0                         ── E: 0     | W: 0     | N: 0                        
✓ broom 0.7.4                            ── E: 0     | W: 0     | N: 0                        
✓ modeltime.resample 0.1.0               ── E: 0     | W: 0     | N: 1                        
✓ modeltime.ensemble 0.3.0               ── E: 0     | W: 0     | N: 1                        
✓ MachineShop 2.6.1                      ── E: 0     | W: 0     | N: 0                        
✓ finetune 0.0.1                         ── E: 0     | W: 0     | N: 1                        
✓ modeltime 0.4.1                        ── E: 0     | W: 0     | N: 1                        
✓ sitar 1.1.2                            ── E: 0     | W: 0     | N: 0                        
✓ stacks 0.1.0                           ── E: 0     | W: 0     | N: 2                        
✓ psfmi 0.7.1                            ── E: 0     | W: 0     | N: 0                        
✓ tfdatasets 2.2.0                       ── E: 0     | W: 0     | N: 0                        
✓ tidymodels 0.1.2                       ── E: 0     | W: 0     | N: 1                        
✓ recipes 0.1.15                         ── E: 0     | W: 0     | N: 0                        
✓ trendeval 0.0.1                        ── E: 0     | W: 0     | N: 0                        
✓ text 0.9.10                            ── E: 0     | W: 0     | N: 1                        
✓ tidyposterior 0.0.3                    ── E: 0     | W: 0     | N: 0                        
✓ tune 0.1.2                             ── E: 0     | W: 0     | N: 0                        
✓ timetk 2.6.1                           ── E: 0     | W: 0     | N: 2                        
OK: 23                                                                                      
BROKEN: 0
Total time: 9 min
```

**Review by juliasilge — APPROVED** [review]
I just 

- installed this PR
- removed the [complement method from spatialsample](https://github.com/tidymodels/spatialsample/blob/master/R/complement.R) so now it just has

```r
#' @importFrom rsample complement
```

- and checked spatialsample with no problems ✅ 

This looks good to me.

**Review by DavisVaughan — APPROVED** [review]
Looks great!

Is there any place where we still use `add_class(at_end = TRUE)`? If not, my only comment would be that you can remove `at_end` altogether (I can't imagine when you'd want to do this anyways)

**Comment by hfrick** [comment]
We don't use `at_end = TRUE` anywhere. Should we open a new issue?

**Comment by DavisVaughan** [comment]
I think just another PR that removes it would be fine if you’d like to tackle it. Otherwise an issue is great!

**Pull request merged**
