### PR TITLE
Update slide.R

### PR DESCRIPTION
**Pull request by mattwarkentin**
I could be wrong, but I think you mean "coarse" not "granular". The original wording gave the opposite impression of what is actually happening.

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Could you please say `less granular`?

Could you also please run `devtools::document()`?

**Comment by mattwarkentin** [comment]
Whoops, I meant to use `/document`. I made this minor edit right on GitHub so I couldn't document the normal way, but I think once the `/document`-triggered GitHub Action finished it will push the changes here.

**Comment by mattwarkentin** [comment]
Okay, this PR turned into a nightmare, let me take a redo on this one. Brb.

**Pull request closed without merging**
