### PR TITLE
Clarify discussion of `strata`

### PR DESCRIPTION
**Pull request by juliasilge**
This PR clarifies how `strata` works, especially with regards to numeric stratification variables. It uses templating to minimize repetition.

### CODE REVIEW

**Review by hfrick — APPROVED** [review]
the reduction of repetition is rather nice :heart_eyes:

**Comment by samuelmacedo83** [comment]
Hi @juliasilge, 
I was reading the documentation about `make_strata` and `vfold_cv` and I'm a lit bit confuse. 
In `make_strata`, the documentation said that numeric variables are divided by [percentile](https://github.com/tidymodels/rsample/blob/62902cb6d9fee3a3b20b24103e5a7b27a6ba5b51/R/make_strata.R#L16), but in `vfold_cv` the numeric variables are divided by [quartile](https://github.com/tidymodels/rsample/blob/62902cb6d9fee3a3b20b24103e5a7b27a6ba5b51/R/vfold.R#L19).

So, even if I use, for example, a 10 fold cv, the numeric variable will be divided by quartiles?

**Comment by juliasilge** [comment]
The function `make_strata()` uses the `stats::quantile()` function with a default of `breaks = 4`, which means quartiles:
https://github.com/tidymodels/rsample/blob/62902cb6d9fee3a3b20b24103e5a7b27a6ba5b51/R/make_strata.R#L119

You can create different bins (e.g. use different percentiles of the data) by changing `breaks`. Maybe we can clarify the `make_strata()` documentation a bit more.

**Comment by samuelmacedo83** [comment]
I think I understood. So the `breaks` parameter on `vfold_cv` is related to how to stratify the variable defined on  `strata` parameter. 
It makes sense :)
thank you @juliasilge

**Pull request merged**
