### PR TITLE
Refactor group logic

### PR DESCRIPTION
**Pull request by mikemahoney218**
This PR is a first step towards addressing #207 , by starting to factor some of the grouping logic out of `group_vfold_cv` and into its own functions. The broad goal here is to support additional functions (particularly `initial_split` and `mc_cv`) by expanding the `switch` statement with additional `balance` arguments. 

This PR shouldn't add any new features or change any behavior, but just reorganizes the grouping internals so that future changes are less invasive. It doesn't need to get in pre-1.0.0, there's no rush here.

### CODE REVIEW

**Review by juliasilge — CHANGES_REQUESTED** [review]
This is a great start to these larger changes! 🙌 

- Can you have the function be `make_groups()`, to parallel `make_strata()`?
- And can you pull that function into a new file `make_groups.R`?

We also should change this filename but I'm not totally sure yet what makes the most sense: `group_vfold.R` vs `vfold_group.R`? If you don't have a strong opinion, let's leave that renaming to when we add a new grouped method.

**Comment by mikemahoney218** [comment]
I was debating asking if we should move it into vfold_cv, and then have future methods also in the same file as their non group methods. Otherwise, not sure what file names would be best!

**Comment by juliasilge** [comment]
Oh, I think I like the idea of each grouped function being in the same file as its ungrouped counterpart! 👍 No need for that here, but for future PRs.

**Comment by juliasilge** [comment]
Should we document and export this like `make_strata()`? 
https://rsample.tidymodels.org/reference/make_strata.html
I think the reason to do this would be so we can `@inheritParams` nicely, and do something like "see [make_groups()]".

**Comment by mikemahoney218** [comment]
I think I'd personally like to _not_ export this if we're merging it pre-1.0.0, because I think we might want to change how the `switch` functions work once we're also providing `group_initial_split` and `group_mc_cv`. 

I haven't thought about this enough to take a stab at implementing it yet, but we also discussed in #300 possibly expanding grouping to take what would effectively be a custom `balance_*` function, which would _probably_ require passing `...` to the `balance_*` functions. That means we might also change how things get passed to `make_groups`, so that different functions can use different arguments -- for instance, we won't need `v` for `group_initial_split`. But I haven't thought enough about what that could look like to even float an implementation yet, and I imagine we'll want to have a bigger discussion about exactly how this all should work in the nearish future.

All that to say, more than happy to document here (and I think we can `@inheritParams` from unexported functions), but I think it'd be nice to wait on exporting this for another version until we get grouping fully implemented.

**Review by juliasilge — APPROVED** [review]
This is a great beginning, and your plan to not export makes good sense. 👍

**Pull request merged**
